### ISSUE TITLE
Invalid JSON string when accessing path "/api/links/Exodus.1"

### ISSUE THREAD

**Issue by moshi100** [Sefaria/Sefaria-Project#398] opened 2018-05-01 20:33 UTC
Hi,

I'm trying to access to "Links" API page but there is an error, when you request to full chapter like "Exodus.1" the string is incomplete and can't converted to JSON, when you access to specific verse everything is OK.

Examples:
200 status link: "https://www.sefaria.org/api/links/Exodus.1.12" Screenshot: http://prntscr.com/jci2uv
Failed status link: "https://www.sefaria.org/api/links/Exodus.1"  Screenshot: http://prntscr.com/jci3ad

This problem is from the last few weeks because it work for me in the past.
Looks like there is a server request limitation, the server block requests that higher then a specific weight so we get an uncompleted string, is there any way we can fix it?

Thanks
Moshe Cohen

**Comment by EliezerIsrael** [comment] 2018-05-02 02:02
Thanks for the error report.  
It was a server configuration issue, and is fixed now.

**Closed by EliezerIsrael** 2018-05-02 02:02 UTC

**Comment by moshi100** [comment] 2018-05-02 08:40
Yes. looks good now, Thanks!

**Comment by moshi100** [comment] 2018-05-10 04:32
Hi, the bug reappears

**Comment by EliezerIsrael** [comment] 2018-05-10 15:10
@moshi100  Thanks for pointing this out.  The issue is our front end caching server.  I've just given it a bit more headroom.  Should be working now.

**Comment by moshi100** [comment] 2018-05-10 19:30
Thanks 👍

**Comment by moshi100** [comment] 2018-05-31 18:27
Ammm again :/

**Comment by EliezerIsrael** [comment] 2018-05-31 18:34
Huh.  Thanks for the heads up.
I'm curious @moshi100 - what are you doing with the API?  Perhaps your usage pattern is stretching us a bit...

**Comment by moshi100** [comment] 2018-05-31 18:44
I have around 100 request per day to your API, using and working great 2 years already.
Everything was OK until 1 month ago, In case it's too heavy let me know and I'll use an alternative :/

**Comment by EliezerIsrael** [comment] 2018-05-31 18:51
The change is due to a new server configuration we have, on one level.  When our cache server (Varnish) is up at the top of its memory limit, it needs to evict objects in order to make room for new ones that come along.  If the new one is very very large, it hits a limit of the number of objects its willing to evict, and gives up.  

I upped those limits, but apparently not enough.  This is making me realize, though, that the `/api/links` is returning very large responses.  

For our own app, we use `/api/related/Exodus.1` - that returns the links but without the text of the linked commentary.  It makes for a much smaller returned object.  Plus - since we use them on our front end, they'd be cached already.   Would that api work for you usage?

**Comment by moshi100** [comment] 2018-05-31 18:57
yes I use `/api/links` and some of the queries are very large like Genesis.1 
I may need to change it to `/api/related/` as you said....
Thanks!

**Comment by moshi100** [comment] 2018-06-01 01:20
Why not use CDN like Cloudflare?
