### ISSUE TITLE
Link Explorer: Non standard behavior on IE

### ISSUE THREAD

**Issue by EliezerIsrael** [Sefaria/Sefaria-Project#121] opened 2015-01-05 15:55 UTC
When links are hovered over, they are highlighted.  That's as should be.  
On IE, they remain highlighted, even after mouse-out.

**Comment by elyashiv** [comment] 2015-03-23 11:01
On what versoins of IE do you get this behaviour?

**Comment by EliezerIsrael** [comment] 2015-03-23 12:07
Good question.  I generally don't use IE.  Every time I did, I saw this issue.

**Comment by alis0nc** [comment] 2017-08-09 16:03
I can reproduce this issue on Internet Explorer 10 on Windows 7. 

![sefaria 121 ie10](https://user-images.githubusercontent.com/4296609/29131276-629a6af6-7cfa-11e7-8916-4c53dd54e541.png)

**Comment by eykanal** [comment] 2017-11-09 20:15
This does not seem to be an issue on IE11 (11.0.9600.18816). Can someone see whether this is still an issue?

**Comment by yishairasowsky** [comment] 2020-04-01 16:07
is this still an issue? i could not reproduce it.

**Comment by blockspeiser** [comment] 2020-05-19 18:28
I'm going to close this issue since we don't have any recent reports of the issue. Thanks.

**Closed by blockspeiser** 2020-05-19 18:28 UTC
Labels: Good First Project, Type: Bug, Zone: Frontend
